language: python
matrix:
  fast_finish: true
  include:
    - env: RUN=run
      os: linux

before_install:
  - if [ "${RUN}" == "run" ]; then
        sudo dpkg --add-architecture i386;
        sudo add-apt-repository --yes ppa:wine/wine-builds;
        sudo apt-get update;
        sudo apt-get install winehq-devel;
    fi;

install:
  - if [ "${RUN}" == "run" ]; then
        sudo apt-get -y install --install-recommends winehq-devel;
        export DISPLAY=:99.0;
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
    fi;

script:
  - if [ "${RUN}" == "run" ]; then
        wine --version;
        cd ~/.wine/drive_c/users/$USERNAME;
        mkdir python && cd python;
        wget -O kiwget.exe https://git.io/vSWf2;
        chmod +x kiwget.exe;
        echo "kiwget kivy";
        wine ./kiwget.exe kivy;
        echo "kiwget kivy end";
        wine cmd /c exit 12345;
    fi;
